# Created by: PyQt6 UI code generator 6.11.0
# Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from pathlib import Path
import re

def set_button(button):
    path = Path(__file__).parent / "autoclick.sh"
    text = path.read_text()

    text = re.sub(
        r'BUTTON=".*?"',
        f'BUTTON="{button}"',
        text
    )

    path.write_text(text)

def set_time(time):
    path = Path(__file__).parent / "autoclick.sh"
    text = path.read_text()

    text = re.sub(
        r'TIME=".*?"',
        f'TIME="{time}"',
        text
    )

    path.write_text(text)


def load_settings(ui):
    path = Path(__file__).parent / "autoclick.sh"
    text = path.read_text()

    variables = dict(re.findall(r'([A-Z_]+)="([^"]*)"', text))

    # Set TIME
    if "TIME" in variables:
        ui.doubleSpinBox.setValue(float(variables["TIME"]))

    # Set BUTTON
    button_map = {
        "0xC0": ui.LeftClick,
        "0xC1": ui.RightClick,
        "0xC2": ui.MidClick,
    }

    if variables.get("BUTTON") in button_map:
        button_map[variables["BUTTON"]].setChecked(True)

icons = Path(__file__).parent / "icons"

class Ui_Manage(object):
    def setupUi(self, Manage):
        Manage.setObjectName("Manage")
        Manage.resize(525, 391)
        Manage.setMinimumSize(QtCore.QSize(525, 391))
        Manage.setMaximumSize(QtCore.QSize(525, 391))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(icons / "e^ipiclicker.svg")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Manage.setWindowIcon(icon)
        Manage.setAutoFillBackground(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Manage)
        self.buttonBox.setGeometry(QtCore.QRect(320, 350, 191, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close|QtWidgets.QDialogButtonBox.StandardButton.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.clicked.connect(self.defaults_clicked)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(parent=Manage)
        self.buttonBox_2.setGeometry(QtCore.QRect(10, 350, 190, 30))
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Help)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.RightClick = QtWidgets.QRadioButton(parent=Manage)
        self.RightClick.setGeometry(QtCore.QRect(390, 30, 91, 141))
        self.RightClick.setStyleSheet(f"""
QRadioButton {{
    background-color: transparent;
    border: 2px solid transparent;
}}

QRadioButton::indicator {{
    image: none;
    width: 0px;
    height: 0px;
}}

QRadioButton {{
    image: url("{icons / 'Rightclick.svg'}");
}}

QRadioButton:checked {{
    image: url("{icons / 'Rightclicked.svg'}");
}}
""")
        self.RightClick.setText("")
        self.RightClick.setIconSize(QtCore.QSize(90, 159))
        self.RightClick.setCheckable(True)
        self.RightClick.setChecked(False)
        self.RightClick.setObjectName("RightClick")
        self.RightClick.clicked.connect(self.RightClick_GotClicked)
        self.MidClick = QtWidgets.QRadioButton(parent=Manage)
        self.MidClick.setGeometry(QtCore.QRect(370, 60, 41, 61))
        self.MidClick.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.MidClick.setStyleSheet("QRadioButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    color: white\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"    background-color: #f0f0f0;\n"
"    border: 2px solid black;\n"
"    color: black\n"
"}\n"
"QRadioButton:indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")

        self.MidClick.setIconSize(QtCore.QSize(47, 124))
        self.MidClick.setCheckable(True)
        self.MidClick.setChecked(False)
        self.MidClick.setAutoExclusive(True)
        self.MidClick.setObjectName("MidClick")
        self.MidClick.clicked.connect(self.MidClick_GotClicked)
        self.LeftClick = QtWidgets.QRadioButton(parent=Manage)
        self.LeftClick.setEnabled(True)
        self.LeftClick.setGeometry(QtCore.QRect(300, 30, 91, 141))
        self.LeftClick.setAutoFillBackground(False)
        self.LeftClick.setStyleSheet(f"""
QRadioButton {{
    background-color: transparent;
    border: 2px solid transparent;
}}

QRadioButton::indicator {{
    image: none;
    width: 0px;
    height: 0px;
}}

QRadioButton {{
    image: url("{icons / 'Leftclick.svg'}");
}}

QRadioButton:checked {{
    image: url("{icons / 'Leftclicked.svg'}");
}}
""")
        self.LeftClick.setText("")
        self.LeftClick.setIconSize(QtCore.QSize(89, 159))
        self.LeftClick.setCheckable(True)
        self.LeftClick.setChecked(True)
        self.LeftClick.setObjectName("LeftClick")
        self.LeftClick.clicked.connect(self.LeftClick_GotClicked)
        self.pushButton_7 = QtWidgets.QPushButton(parent=Manage)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 170, 201, 141))
        self.pushButton_7.setStyleSheet(f"""
QPushButton {{
    border: none;
}}
QPushButton:checked {{
    border: none;
}}
QPushButton {{
    image: url("{icons / 'ebottom.svg'}");
}}
""")
        self.pushButton_7.setText("")
        self.pushButton_7.setIconSize(QtCore.QSize(183, 159))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setChecked(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame = QtWidgets.QFrame(parent=Manage)
        self.frame.setGeometry(QtCore.QRect(40, 110, 231, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.doubleSpinBox.setGeometry(QtCore.QRect(30, 50, 162, 81))
        self.doubleSpinBox.setStyleSheet("QDoubleSpinBox {\n"
"font-size: 24px\n"
"}")
        self.doubleSpinBox.setProperty("value", 15.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox.valueChanged.connect(self.Time_GotChanged)
        self.ktextedit = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.ktextedit.setGeometry(QtCore.QRect(40, 0, 141, 41))
        self.ktextedit.setStyleSheet("QPlainTextEdit {\n"
"background: transparent;\n"
"font-size: 24px\n"
"}")
        self.ktextedit.setObjectName("ktextedit")
        self.buttonBox.raise_()
        self.buttonBox_2.raise_()
        self.RightClick.raise_()
        self.LeftClick.raise_()
        self.pushButton_7.raise_()
        self.MidClick.raise_()
        self.frame.raise_()

        self.retranslateUi(Manage)
        self.buttonBox.accepted.connect(Manage.accept) # type: ignore
        self.buttonBox.rejected.connect(Manage.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Manage)

    def retranslateUi(self, Manage):
        _translate = QtCore.QCoreApplication.translate
        Manage.setWindowTitle(_translate("Manage", "Etotheipi autoclicker"))
        self.MidClick.setText(_translate("Manage", "Mid"))
        self.doubleSpinBox.setSuffix(_translate("Manage", "ms"))
        self.ktextedit.setPlainText(_translate("Manage", "Click every:"))


    def LeftClick_GotClicked(self):
        set_button("0xC0")
    def RightClick_GotClicked(self):
        set_button("0xC1")
    def MidClick_GotClicked(self):
        set_button("0xC2")

    def Time_GotChanged(self, value):
        set_time(value)

    def defaults_clicked(self, button):
        if self.buttonBox.standardButton(button) == QtWidgets.QDialogButtonBox.StandardButton.RestoreDefaults:
            self.doubleSpinBox.setValue(15)
            self.LeftClick.setChecked(True)
            set_button("0xC0")

import sys
from PyQt6.QtWidgets import QApplication, QDialog

app = QApplication(sys.argv)

Manage = QDialog()
ui = Ui_Manage()
ui.setupUi(Manage)
load_settings(ui)
Manage.show()
sys.exit(app.exec())
